/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.UIManager;
import laboratorio01.Curso;
import laboratorio01.Estudiante;

/**
 *
 * @author admin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdAgregarEstudiante = new javax.swing.JButton();
        cmdCurso = new javax.swing.JButton();
        cmdCalificaciones = new javax.swing.JButton();
        cmdCuestionario = new javax.swing.JButton();
        cmdPreguntas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdAgregarEstudiante.setText("Agregar Estudiantes");
        cmdAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(cmdAgregarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 130, 30));

        cmdCurso.setText("Curso");
        cmdCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCursoActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, 30));

        cmdCalificaciones.setText("Calificaciones");
        cmdCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalificacionesActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, 30));

        cmdCuestionario.setText("Cuestionarios");
        cmdCuestionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCuestionarioActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCuestionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 30));

        cmdPreguntas.setText("Prenguntas");
        cmdPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPreguntasActionPerformed(evt);
            }
        });
        jPanel1.add(cmdPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, 30));

        jMenu1.setText("File ");

        jMenuItem1.setText("Calificacion");
        jMenu1.add(jMenuItem1);

        jMenu2.setText("Cuestionaro");

        jMenuItem2.setText("Lista Preguntas");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Lista Calificaciones");
        jMenu2.add(jMenuItem3);

        jMenu1.add(jMenu2);

        jMenu3.setText("Curso");

        jMenuItem4.setText("Lista Estudiantes");
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenuItem5.setText("Pregunta");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Estudiante");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCursoActionPerformed
        GuiCurso obj = new GuiCurso();
        obj.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_cmdCursoActionPerformed

    private void cmdAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarEstudianteActionPerformed
        this.dispose();   
        GuiEstudiante abrir = new GuiEstudiante();
        abrir.setVisible(true);
      
    }//GEN-LAST:event_cmdAgregarEstudianteActionPerformed

    private void cmdCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalificacionesActionPerformed
      GuiCalificaciones obj = new GuiCalificaciones();
       obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCalificacionesActionPerformed

    private void cmdCuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCuestionarioActionPerformed
        GuiCuestionario obj = new GuiCuestionario();
        obj.setVisible(true);
        
    }//GEN-LAST:event_cmdCuestionarioActionPerformed

    private void cmdPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPreguntasActionPerformed
        GuiPregunta obj = new GuiPregunta();
       obj.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_cmdPreguntasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregarEstudiante;
    private javax.swing.JButton cmdCalificaciones;
    private javax.swing.JButton cmdCuestionario;
    private javax.swing.JButton cmdCurso;
    private javax.swing.JButton cmdPreguntas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
