/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author admin
 */
public class UiLogin extends javax.swing.JFrame {
private Timer tiempo;
int cont;
public final static int TWO_SECOND=5;
    /**
     * Creates new form UiLogin
     */
    public UiLogin() {
        initComponents();
        setLocationRelativeTo(null);
        jProgressBar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCuentaNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblnombre = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblcontraseña = new javax.swing.JLabel();
        txtCuentaContraseña = new javax.swing.JPasswordField();
        cmdSignup = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCuentaNombre.setBackground(new java.awt.Color(0, 0, 51));
        txtCuentaNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtCuentaNombre.setBorder(null);
        jPanel2.add(txtCuentaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 207, 22));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 207, 23));

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(0, 51, 102));
        lblnombre.setText("Nombre:");
        jPanel2.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 207, 23));

        lblcontraseña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcontraseña.setForeground(new java.awt.Color(0, 51, 102));
        lblcontraseña.setText("Contraseña:");
        jPanel2.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtCuentaContraseña.setBackground(new java.awt.Color(0, 0, 51));
        txtCuentaContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtCuentaContraseña.setText("++++++++++++++");
        txtCuentaContraseña.setBorder(null);
        txtCuentaContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuentaContraseñaKeyPressed(evt);
            }
        });
        jPanel2.add(txtCuentaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 207, 22));

        cmdSignup.setBackground(new java.awt.Color(0, 51, 102));
        cmdSignup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdSignup.setForeground(new java.awt.Color(255, 255, 255));
        cmdSignup.setText("Sign up");
        cmdSignup.setBorder(null);
        cmdSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSignupActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 207, 50));

        jProgressBar.setBackground(new java.awt.Color(0, 0, 51));
        jProgressBar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jProgressBar.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\laboratorio\\Imagenes\\icons8-user.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 110, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 390, 490));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Laboratorio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("proyecto final algoritmos 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(259, 259, 259))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSignupActionPerformed
          IniciarSeccion();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSignupActionPerformed

    private void txtCuentaContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaContraseñaKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            IniciarSeccion();
        }
    }//GEN-LAST:event_txtCuentaContraseñaKeyPressed
      
    /**
     * @param args the command line arguments
     */
    class TimerListener implements ActionListener{

        public void actionPerformed(ActionEvent e) {
         cont++;
         jProgressBar.setValue(cont);
         if(cont==100){
             tiempo.stop();
             esconder();
             Principal abrir = new Principal();
            abrir.setVisible(true);
            setVisible(false);
         }
        }
    }
   public void esconder(){this.setVisible(false);}
   public void activar(){tiempo.start();}
    public void IniciarSeccion(){
        String usuario=txtCuentaNombre.getText();
        String contraseña=String.valueOf(txtCuentaContraseña.getPassword());
        
        if(usuario.equals("admin")&& contraseña.compareTo("root123")==0){
           jProgressBar.setVisible(true);
            cont=-1;
           jProgressBar.setValue(0);
           jProgressBar.setStringPainted(true);
           tiempo = new Timer(TWO_SECOND, (ActionListener) new TimerListener());
           activar();
        }else{
           JOptionPane.showMessageDialog(null,"Error al ingresar, usuario o contraseña son incorrectos");
        }
    }   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UiLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JPasswordField txtCuentaContraseña;
    private javax.swing.JTextField txtCuentaNombre;
    // End of variables declaration//GEN-END:variables
}
